version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: List Files
          command: |
            cd /home/circleci/project
            ls -lh
      - run:
          name: Package Requirements
          command: |
            pip install --target ./package -r requirements.txt
      - run:
          name: Zip Requirements
          command: |
            cd package
            zip -r ../themorningreport-package.zip .
      - run:
          name: Add Applicaition Files to Package
          command: |
            cd ..
            zip -gr themorningreport-package.zip .
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
  deploy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Create TF Creds File
          command: |
            mkdir ~/.terraform.d
            echo "{\"credentials\": {\"app.terraform.io\": {\"token\": \"${TF_LOGIN_DEV}\"}}}" > ~/.terraform.d/credentials.tfrc.json
            cat ~/.terraform.d/credentials.tfrc.json
      - run:
          name: Create AWS Creds File
          command: |
            mkdir ~/.aws
            echo "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
      - run:
          name: Terraform Init
          command: |
            cd infrastructure
            terraform init
      - run:
          name: Terraform Apply
          command: |
            terraform apply -auto-approve

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

